### ISSUE TITLE
Node Settings

### ISSUE THREAD

**Issue by CrackTheCode016** [aleixmorgadas/nem2-wallet-browserextension#8] opened 2019-03-10 17:16 UTC
This is a suggestion that I was thinking to add to this wallet. I was thinking the user should be allowed to pick which node they can use for sending transactions in the `send` tab.  

**I see two approaches:** 

 - Create a separate settings tab, or 

 - Or, make it part of `home` or `wallet` tab.  

This node URL can be used globally throughout the extension to send signed transactions via `TransactionHttp`, and allow us to easily test sending various transaction types.  Of course, this approach will probably change later on with a drop-down list of nodes for public catapult, but for now this was what I was thinking.

**Comment by aleixmorgadas** [comment] 2019-03-10 18:57
My approach for `cw-extension` is **simple by design.** It's not only about the user experience, it's about the code and how we define the features.

I would recommend you do the minimal work each time you want to contribut to `cw-extension`. The idea is that smaller patches are better than bigger features.

At the beginning, I would suggest make the URL part of the "Wallet". Later, we can add a drop down list with the servers or something better when we design the feature.

**Comment by aleixmorgadas** [comment] 2019-03-28 21:00
I close this issue since now there is a shared state ^^

**Closed by aleixmorgadas** 2019-03-28 21:00 UTC
Labels: question
